name: medi_track
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.1
  gap: ^3.0.1
  intl: ^0.18.1

  # State Management
  hooks_riverpod: ^2.3.7

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Notifications
  flutter_local_notifications: ^15.1.1
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.2

  # Others
  go_router: ^10.0.0
  permission_handler: ^11.3.1
  uuid: ^4.3.3
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
